### ISSUE TITLE
aws-ebs times out waiting for WinRM

### ISSUE THREAD

**Issue by aduric** [packer-community/packer-windows-plugins#11]
Using the Base Windows Server 2008 R2 SP1 source image (ami-f8ff9b90), packer builder times out waiting for WinRM. With debug mode on, I was able to get some output:

==> amazon-windows-ebs: Waiting for WinRM to become available...
2014/12/23 02:07:30 packer-builder-amazon-windows-ebs: 2014/12/23 02:07:30 Configured remote WinRM address to be <IPv4>:5985
2014/12/23 02:07:30 packer-builder-amazon-windows-ebs: 2014/12/23 02:07:30 Attempting WinRM connection (timeout: 20m0s)
2014/12/23 02:09:38 packer-builder-amazon-windows-ebs: 2014/12/23 02:09:38 WinRM connection err: unknown error Post http://<IPv4>:5985/wsman: dial tcp <IPv4>:5985: connection timed out
2014/12/23 02:09:43 packer-builder-amazon-windows-ebs: 2014/12/23 02:09:43 Configured remote WinRM address to be <IPv4>:5985
2014/12/23 02:09:43 packer-builder-amazon-windows-ebs: 2014/12/23 02:09:43 Attempting WinRM connection (timeout: 20m0s)
2014/12/23 02:09:46 packer-builder-amazon-windows-ebs: 2014/12/23 02:09:46 WinRM connection err: http error: 401 -

...And so on.

Does anything need to be configured in the base image for WinRM to work properly?

**Comment by fivetanley** [comment]
@mefellows I am sorry to bump an old issue, but I removed these two lines here.. https://gist.github.com/mefellows/0373408377337ab62ff5#file-winrm-packer-community-json-L15-L16 Are they necessary for the example script to work? I'm also getting winRM timeouts

**Comment by mefellows** [comment]
Hi @fivetanley which AMI are you using? If I recall, the standard Windows 2012r2 AMI (the one in that script looks to be out of date and deregistered) is required to be setup within a VPC and therefore a subnet (the default VPC should suffice) - the ones provided will obviously need to change, and allow access to port `5985` from your location. Its worth checking to see these network ACLs as they're likely the cause if everything else is the same.

**Comment by fivetanley** [comment]
@mefellows Turns out it was some weird thing around the password... For only reason some variations of `Hi@Taco123` from @dylanmei's example repository work. Haven't figured out the reason why yet.

**Comment by davidvasandani** [comment]
@mefellows with `amazon-window-ebs` being depreciated in 0.8 I'm trying to get a simple Packer build to work.

https://gist.github.com/davidneudorfer/d65286528c116a2091b4

I tried both .ps1 files as the `user_data_file` variable in `packer.json` but it doesn't seem to run either (I don't see any of the expected output) before beginning to wait for WinRM.

```
2015/09/21 21:55:58 packer-builder-amazon-ebs: 2015/09/21 21:55:58 [INFO] Attempting WinRM connection...
2015/09/21 21:55:58 packer-builder-amazon-ebs: 2015/09/21 21:55:58 [DEBUG] connecting to remote shell using WinRM
2015/09/21 21:57:13 packer-builder-amazon-ebs: 2015/09/21 21:57:13 [ERROR] connection error: unknown error Post http://ec2-50-16-24-31.compute-1.amazonaws.com:5985/wsman: dial tcp 50.16.24.31:5985: getsockopt: operation timed out
2015/09/21 21:57:13 packer-builder-amazon-ebs: 2015/09/21 21:57:13 [ERROR] WinRM connection err: unknown error Post http://ec2-50-16-24-31.compute-1.amazonaws.com:5985/wsman: dial tcp 50.16.24.31:5985: getsockopt: operation timed out
```

**Comment by mefellows** [comment]
Hi @davidneudorfer, have you launched this into a VPC? Can you confirm that there is a network path to where you need to get to? Oftentimes the problem is the networking around the instance itself.

That being said, can you check the console logs to see if the user-data script ran?

**Comment by davidvasandani** [comment]
Thanks for the suggestions @mefellows. The instance is inside of a VPC.

These are the Packer logs
https://gist.github.com/davidneudorfer/3c256c3ad2cdd71d2289

This is the EC2 System Log, it looks like the user_data_script did not run.

```
2015/09/22 11:37:40Z: EC2ConfigMonitorState: 0
2015/09/22 11:37:40Z: Windows sysprep configuration complete.
2015/09/22 11:37:43Z: AMI Origin Version: 2015.09.09
2015/09/22 11:37:43Z: AMI Origin Name: Windows_Server-2012-R2_RTM-English-64Bit-Base
2015/09/22 11:37:43Z: OS: Microsoft Windows NT 6.3.9600
2015/09/22 11:37:43Z: OsVersion: 6.3
2015/09/22 11:37:43Z: OsProductName: Windows Server 2012 R2 Standard
2015/09/22 11:37:43Z: OsBuildLabEx: 9600.17936.amd64fre.winblue_ltsb.150715-0840
2015/09/22 11:37:43Z: Language: en-US
2015/09/22 11:37:43Z: EC2 Agent: Ec2Config service v3.9.359
2015/09/22 11:37:44Z: Message: Waiting for meta-data accessibility...
2015/09/22 11:37:44Z: Message: Meta-data is now available.
2015/09/22 11:37:45Z: AMI-ID: ami-c9cea0ac
2015/09/22 11:37:45Z: Instance-ID: i-da5e0e79
2015/09/22 11:37:48Z: Driver: AWS PV Network Device v7.3.2.0
2015/09/22 11:37:48Z: Driver: AWS PV Storage Host Adapter v7.3.2.0
2015/09/22 11:37:48Z: Ec2SetPassword: Enabled
2015/09/22 11:37:49Z: RDPCERTIFICATE-SUBJECTNAME: WIN-NT5LAT0FP5M
2015/09/22 11:37:49Z: RDPCERTIFICATE-THUMBPRINT: C31EABFA4AD17A987E3FC940B5F46C1A5E753D0C
2015/09/22 11:37:52Z: Username: Administrator
2015/09/22 11:37:52Z: Password: <Password>
UErXtKWVOD6bu93I0W1DKlYMXdiIRWvJC0gzrKKVeHfhD1hXaB4e3hn7eOmWLwX37+lmfpbpsfXbc+UcvFOkOp6Ym2R26x1BRySQq8XCAuE6tkfdHv5xtLO2nF7XdfC3rn5Vwvi+wjpubk2twQCn0kRATmfI7yec8jsgkUezSdj9zTJCabHrMvh1PO/4vmqyt2yL6rssgyQwfTMgA48T8lHGptvDe4GF0JkdIa+udgkNbiM0rO40Kx+93Jq9oL8vGOhw5o5zgs3H0x3cOQYoJJl5ABrs11alT0OalBAsgWBXIqQUfxw8cl2Ykf4KPM+pGo4bp24fHBNmb9PbZGZOLA==
</Password>
2015/09/22 11:37:53Z: Message: Windows is Ready to use
```

After updating the security group to allow port 3389 I was able to RDP into the instance and ping Google.
![image](https://cloud.githubusercontent.com/assets/547876/10018375/45f161ca-6104-11e5-9db6-9e2d1199383f.png)

Packer still hangs while waiting for WinRM and as far as I can tell never runs the `user_data_file` script.

This is an interesting event Windows Event Viewer:
https://gist.github.com/davidneudorfer/bd6898333ab0c4b488df

**Comment by mefellows** [comment]
That Event Viewer is quite interesting, I've never seen that before. 

With respect to `ami-c9cea0ac` - how is that created? Have you tried this on a vanilla/OOTB amazon AMI? Unless you explicitly create the AMI with the ability to run user-data again, it won't run it - which is possibly what you're running into.

Check out http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/UsingConfig_WinAMI.html#user-data-execution for more detail on this.
