### ISSUE TITLE
Powershell provisioner

### ISSUE THREAD

**Issue by dylanmei** [packer-community/packer-windows-plugins#12]
This is a follow-up on PR #9 

With inline commands, the docs for the stock shell provisioner say, "...the commands are concatenated by newlines and turned into a single file, so they are all executed within the same context. This allows you to change directories in one command and use something in the directory in the next and so on. Inline scripts are the easiest way to pull off simple tasks within the machine."

So one or more inline commands should work the same way as running individual scripts, and the following should be possible:

    "type": "windows-shell",
    "environment_vars": ["HELLO_DIR=C:\\Hello"],
    "inline": [
        "cd $env:HELLO_DIR",
        "Add-Content Hello.txt -Value \"Hello $env:PACKER_BUILDER_TYPE\"",
        "Test-Path -Path $env:HELLO_DIR\Hello.txt"
    ]

I feel that this is desirable behavior.

But it's not possible at the moment, because Powershell statements must be preceded by "powershell.exe". The `windows-shell` provisioner always runs against cmd.exe. It is impractical to guess if the inline commands are for cmd.exe or powershell.exe

Having a strict Powershell-only provisioner allows us to:

1) Support the "same context" behavior of stock shell-provisioner when handling inline powershell statements

2) Clean up inline commands such as installing chocolatey, from @mefellows [sample ec2 gist](https://gist.github.com/mefellows/0373408377337ab62ff5). From this

      "type":"windows-shell",
      "inline": [
        "powershell -command \"iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))\"",
        "powershell -command \"choco install seek-dsc\""
        ]

to this:

      "type":"powershell",
      "inline": [
        "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))",
        "choco install seek-dsc"
        ]

3) Take on other special properties without polluting the stock shell provisioner. The property I'm thinking of is:

      "type":"powershell",
      "start_elevated": true,
      "inline": [
        "format C:"
        ]

**Comment by mefellows** [comment]
Yes, this is probably a better proposal than the `-EncodedCommand` alternative I was thinking of and there is much by the way of re-use we can get. 

In terms of implementation, what are your thoughts on paramaterizing the current provisioner further rather than creating a new one altogether?  @sneal takes a similar approach in his [PR](https://github.com/mitchellh/packer/pull/1245/files#diff-7146f921e5be4ed1447e430da78125a7R35) Or perhaps we could export another provisioner that simply wraps the current one with those parameters already set to a 'powershell mode' default.

**Comment by dylanmei** [comment]
Personally, I'm in favor of a Powershell-specific communicator because it's very intention revealing and you can make the assumption that you are using the WinRM communicator. 

Shawn's chef and shell provisioner PRs have been sitting in mitchellh/packer for awhile. There's this oddity about trying to tell the provisioners what guest OS (or more importantly, which communicator) they're running on, and I am guessing that's what the holdup is.

But that's just my opinion and I very much wonder what other stakeholders think.

**Comment by dylanmei** [comment]
Regarding packer `guest_os_type` / `communicator_type` config, see @sneal and @rasa comments on this PR: https://github.com/mitchellh/packer/pull/1180

**Comment by mefellows** [comment]
Closing due to PR #15.
