### ISSUE TITLE
Works with 2012r2, doesnt work with 2008r2

### ISSUE THREAD

**Issue by ramarnat** [packer-community/packer-windows-plugins#14]
inline works on both.
winrm running a powershell script is independently confirmed to work on both using a command line golang lib, so the access is denied is strange. 

I suspect that for some reason the upload is failing to actually write the file. Looking in the C:\Windows\Temp directory, I find a zero byte xxxx.dmp file.

on 2012r2
```
==> vmware-windows-iso: Provisioning with shell script: install-7zip.ps1
2015/01/10 18:50:51 packer-provisioner-windows-shell: 2015/01/10 18:50:51 Opening install-7zip.ps1 for reading
2015/01/10 18:50:51 packer-provisioner-windows-shell: 2015/01/10 18:50:51 [INFO] 298 bytes written for 'uploadData'
2015/01/10 18:50:51 [INFO] 298 bytes written for 'uploadData'
2015/01/10 18:50:57 packer-builder-vmware-windows-iso: 2015/01/10 18:50:57 starting remote command:  powershell -Command c:/Windows/Temp/script.ps1
2015/01/10 18:51:02 packer-builder-vmware-windows-iso: 2015/01/10 18:51:02 [INFO] RPC endpoint: Communicator ended with: 0
```

on 2008r2
```
==> vmware-windows-iso: Provisioning with shell script: install-7zip.ps1
2015/01/10 18:39:07 packer-provisioner-windows-shell: 2015/01/10 18:39:07 Opening install-7zip.ps1 for reading
2015/01/10 18:39:07 packer-provisioner-windows-shell: 2015/01/10 18:39:07 [INFO] 298 bytes written for 'uploadData'
2015/01/10 18:39:07 [INFO] 298 bytes written for 'uploadData'
2015/01/10 18:39:07 packer-builder-vmware-windows-iso: <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="5" Machine="VAGRANT-H77FAIN"><f:Message>Access is denied. </f:Message></f:WSManFault>
2015/01/10 18:39:07 packer-builder-vmware-windows-iso: Error number:  -2147024891 0x80070005
2015/01/10 18:39:07 packer-builder-vmware-windows-iso: Access is denied.
```

**Comment by dylanmei** [comment]
Funny, I was *just* confirming the WinRM file upload problem on 2008 R2. There's an ongoing conversation in Issue https://github.com/packer-community/packer-windows-plugins/issues/3 where this was also brought up. I'll create a corresponding issue in [packer-community/winrmcp](https://github.com/packer-community/winrmcp) shortly.

**Comment by dylanmei** [comment]
I've addressed the inability to perform any file uploads while working on https://github.com/packer-community/winrmcp/issues/3.

@ramarnat That issue remains open, but please close this issue if everything checks out for you. Let me know if you need new release binaries.

**Comment by ramarnat** [comment]
Thanks that worked.
