### ISSUE TITLE
Create Chocolatey package

### ISSUE THREAD

**Issue by mefellows** [packer-community/packer-windows-plugins#17]
Create a Chocolatey package to make installation on Windows machines easier.

**Comment by mefellows** [comment]
Package created (and in the process noticed an issue in Packer docu - plugins should go in the %APPDATA\packer.d\plugins directory on Windows) https://chocolatey.org/packages/PackerCommunityPlugins/0.0.9-alpha

Once the moderator approves, I'll make the corresponding updates to README.

**Comment by Thermatix** [comment]
Is it "safe" to install these plugins via chocolatey using the alpha package?

**Comment by mefellows** [comment]
Hi @Thermatix, I can give any guarantees but I really don't see it being 'unsafe'. As you note the software that is currently packaged is pre-release, which just means that it doesn't contain all of the features and there are likely some bugs (we're in the process of working through a stable release) - you could manually install it from [here](https://github.com/packer-community/packer-windows-plugins/releases). There is nothing else in the chocolatey script if you're concerned about virus' etc.

**Comment by Thermatix** [comment]
I see, the reason I ask is I need to be able to install via chef, if I can't use the chocolatey package then I'd have to remote the file, extract it, get it to where it needs to go, not difficult but very tedious.

**Comment by mefellows** [comment]
I would say that is perfectly safe and reasonable thing to do @Thermatix. Take a look at the [install](https://github.com/packer-community/packer-community-chocolatey/blob/master/Tools/ChocolateyInstall.ps) file if you're really concerned (you can see that it just uses the OOTB Chocolatey unzipper on the current release).

**Comment by Thermatix** [comment]
In the end we moved the zip file to a chocolatey package and host it on internal artifactory and just install the zip from there, but thanks for the help, much appreciated.

**Comment by mefellows** [comment]
Submitted 1.0.0 release to Nuget/Chocolatey last night, now awaiting moderation. Closing for now.
