### ISSUE TITLE
Powershell provisioner exit status

### ISSUE THREAD

**Issue by pall-valmundsson** [packer-community/packer-windows-plugins#34]
I had issues using the powershell provisioner. When an exception is thrown or the exit code for any reason is anything else than zero it's ignored and building happily continues and you probably don't get the box you expected.

I "fixed it" by overriding `execute_command` with `"powershell \"& { {{.Vars}}{{.Path}}; exit $LastExitCode }\""`. I'm not proficient enough in Go to confidently submit a PR, but I would guess [this](https://github.com/packer-community/packer-windows-plugins/blob/master/provisioner/powershell/provisioner.go#L118) needs changing.

**Comment by mefellows** [comment]
Thanks @pall-valmundsson, I've seen a few strange issues like this recently myself - I'll look at this shortly. 

Looks like someone literally created a similar bug #35.

**Comment by mefellows** [comment]
Put together simple test case for this at https://gist.github.com/mefellows/32e5ca354a6c3255bc16 which I'm working to make pass locally.

**Comment by mefellows** [comment]
Closed due to #36
