### ISSUE TITLE
Restart provisioner (seems to) ignore restart_command

### ISSUE THREAD

**Issue by qmfrederik** [packer-community/packer-windows-plugins#42]
I was very happy when I noticed the restart provisioner has a restart_command, that seemed to allow me to customize which command is executed when restarting the VM -- similar to the shutdown_command.

Unfortunately, it appears the provisioner actually ignores the value of that property, and always uses the default command (cfr. line 89 of restart/provisioner.go).

Frederik.

**Comment by mefellows** [comment]
Hi @qmfrederik, good pickup. I'll fix ASAP.

**Comment by mefellows** [comment]
Fixed & deployed another [RC](/packer-community/packer-windows-plugins/releases/tag/v1.0.0-rc). That should do the trick. Will close this one off.

Appreciate the bug report!
