### ISSUE TITLE
Floppy files doesn't allow for the same URI format as iso_url

### ISSUE THREAD

**Issue by colinbowern** [packer-community/packer-windows-plugins#47]
The template has different rules for file paths which makes it difficult to manage.  When referring to files the same rules should apply to floppy_files collection as it does to the iso_url field. Trying the file:/// format results in the following errors:

    Build 'vmware-windows-iso' errored: Error adding file to floppy: GetFileAttributesEx file:///C:/Users/colinb/Projects/BaseBoxes/Keys/CertificateAuthority.crt: The filename, directory name, or volume label syntax is incorrect.

Please use consistent path parsing across all of packer and its plugins.

**Comment by dylanmei** [comment]
This behavior comes from Packer. From the documentation on [packer.io](https://packer.io/docs/builders/vmware-iso.html):

```
floppy_files (array of strings) - A list of files to place onto a floppy disk that is attached when the VM is booted. ... All files listed in this setting get placed into the root directory of the floppy and the floppy is attached as the first floppy device. ... Wildcard characters (*, ?, and []) are allowed. Directory names are also allowed, which will add all the files found in the directory to the floppy.
```

It would be odd to try to support paths with wildcards and URLs.

**Comment by mefellows** [comment]
Yeah it's a bit of a strange one. The best we could offer would be to simplify the floppy files behaviour which would make us divergent from upstream Packer. As we have a goal to some day merge this into upstream Packer I'm not sure this is a good idea I'm afraid to say.

**Comment by dylanmei** [comment]
@colinbowern please address this as an issue at [mitchellh/packer](http://github.com/mitchellh/packer) and we'll gladly follow along. Until then, we're not going to diverge our behavior here.
