### ISSUE TITLE
Install VMware Tools via VIX API, not WinRM copy

### ISSUE THREAD

**Issue by colinbowern** [packer-community/packer-windows-plugins#55]
The WinRM copy process is so slow.  Does it make more sense to use the [VMware VIX API](https://www.vmware.com/support/developer/vix-api/vix113_reference/index2.html) to push the tools in via ISO mount?

**Comment by mefellows** [comment]
Hi Colin, unfortunately whilst there are plenty of strategies we could employ to speed up uploads / guest additions it complicates our plugin process as each plugin would require a different implementation and therefore maintenance etc. 

That being said we would consider pull requests to improve the situation.. :)

**Comment by dylanmei** [comment]
The copy process is slow. In a pinch, you can edit your template to skip the automatic upload and add a provisioning script that pulls it down via http, for example: [https://github.com/dylanmei/packer-windows-templates/blob/master/scripts/vmware-tools.ps1.example](https://github.com/dylanmei/packer-windows-templates/blob/master/scripts/vmware-tools.ps1.example)

**Comment by mefellows** [comment]
Ima close this one off - feel free to raise a PR or look at Dylan's suggestion.
