### ISSUE TITLE
 Unknown configuration key: "version"

### ISSUE THREAD

**Issue by skylock** [packer-community/packer-windows-plugins#64]
I receive the above error when trying to specify key "version" : "8"

**Comment by petertornyi** [comment]
I guess you are trying to use the builder vmware-windows-iso. The "version" option is not available in this builder. I know that it is working in default vmware-iso, but somehow it is missing from the windows version.

**Comment by skylock** [comment]
You are right, I am trying to use the builder vmware-windows-iso. Can it be fixed ?

**Comment by petertornyi** [comment]
I was trying to check out the source and play with the version option but I was running into failing dependencies (packer.ConfigTemplate).
I saw  dylanmei mentioning that the main packer is going through a refractoring, I think this is not the best moment to add functions to plugins.
