### ISSUE TITLE
stops attempting to connect to winrm even before the timeout

### ISSUE THREAD

**Issue by paramadeep** [packer-community/packer-windows-plugins#66]
Hi,

while running my packer build this is the following log that I get. It tries to connect to winrm couple of time and stops there forever, even beyond the time out time. While in virtualbox the windows gets installed, winrm enabled and restarted and wait there.

2016/08/21 16:54:24 packer: 2016/08/21 16:54:24 Waiting for WinRM, up to timeout: 15m0s
2016/08/21 16:54:24 ui: ==> virtualbox-iso: Waiting for WinRM to become available...
==> virtualbox-iso: Waiting for WinRM to become available...
2016/08/21 16:54:29 packer: 2016/08/21 16:54:29 [INFO] Attempting WinRM connection...
2016/08/21 16:54:29 packer: 2016/08/21 16:54:29 [DEBUG] connecting to remote shell using WinRM
2016/08/21 16:55:45 packer: 2016/08/21 16:55:45 [ERROR] connection error: unknown error Post http://127.0.0.1:2910/wsman: EOF
2016/08/21 16:55:45 packer: 2016/08/21 16:55:45 [ERROR] WinRM connection err: unknown error Post http://127.0.0.1:2910/wsman: EOF
2016/08/21 16:55:50 packer: 2016/08/21 16:55:50 [INFO] Attempting WinRM connection...
2016/08/21 16:55:50 packer: 2016/08/21 16:55:50 [DEBUG] connecting to remote shell using WinRM
2016/08/21 16:57:06 packer: 2016/08/21 16:57:06 [ERROR] connection error: unknown error Post http://127.0.0.1:2910/wsman: EOF
2016/08/21 16:57:06 packer: 2016/08/21 16:57:06 [ERROR] WinRM connection err: unknown error Post http://127.0.0.1:2910/wsman: EOF

I'm using OSX 10.12 Beta (16A270f), Packer 0.10.1. Please help me, how to debug this further.

**Comment by paramadeep** [comment]
I had to recompile packer from source code in OSX 10.12 Beta. it worked then. Thanks.

**Comment by mefellows** [comment]
Thanks for following this up @paramadeep, glad to hear you got it sorted. Do you understand why a full rebuild is required?
