### ISSUE TITLE
Error when Powershell provisioner environment variable value contains =

### ISSUE THREAD

**Issue by maniSbindra** [packer-community/packer-windows-plugins#68]
* Description
 When trying to pass parameter to powershell script with Powershell provisioner, if the parameter value has “==” in it, the packer build fails with error “Shell provisioner environment variables must be in key=value”.

* Packer Version : 0.12.0

* Sample Provisioner script to Reproduce Error:
``` Powershell Provisioner with environment variables set
.
.
  {
            "type": "powershell",
            "scripts": ["IIS_Common2.ps1"],
            "environment_vars":["SECRET_KEY={{user `SECRET_KEY`}}"]
  }
.
.
```

``` SampleValue of SECRET-KEY
SECRET_KEY=osdfasdfasdfasdfasYUsdfsOx+sdfsdfadZk/ud2asdff1I+UYasdfasdfasdfasdfasdfSU4DDFDSCd2sMGGQ==
```

Same error received even when == in SECRET_KEY replaced by \=\=
if == is removed packer build executes without any error

**Comment by mefellows** [comment]
Thanks for raising this. Note this repository is mostly inactive and has been moved to mitchellh/packer, have you considered upgrading?

**Comment by maniSbindra** [comment]
Thanks, I tried with version 0.12.3, I think the issue is resolved.
